use_frameworks!

platform :ios, '12.0'

target 'onesecondbefore-tracker_Example' do
  pod 'onesecondbefore-tracker', :path => '../'
  pod 'FirebaseAnalytics'

end

post_install do |pi|
    pi.pods_project.targets.each do |t|
        t.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
    end
end
